import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import MyProfilepic from "@/components/MyProfilepic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar />
        <MyProfilepic />
        {children}
      </body>
    </html>
  );
}
