export const data = {
  products: [
    {
      id: "1",
      name: "polo shirt",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "2",
      name: "polo shirt",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "3",
      name: "polo shirt",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "4",
      name: "polo shirt",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "5",
      name: "polo shirt",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "6",
      name: "polo shirt",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};
